baseURL = "https://sharpstone.blog/"
languageCode = "en-us"
title = "Sharpstone Blog"
theme = "mainroad"

[params]
  description = "Articles and insights from Sharpstone"
  copyright = "© 2025 Randy Haas / The Sharpstone Group LLC"
  opengraph = true  # For social media previews
  twitter_cards = true
  readmore = true   # Adds "Read More" links

[[menu.main]]
  name = "Home"
  url = "/"
[[menu.main]]
  name = "Posts"
  url = "/posts/"